### ISSUE TITLE
DDR4 SDRAM - Understanding the Basics

### ISSUE THREAD

**Issue by jerryduan100** [subbdue/systemverilog.io#16]
### Discussed in https://github.com/subbdue/systemverilog.io/discussions/2

<div type='discussions-op-text'>

<sup>Originally posted by **subbdue** February 23, 2023</sup>
Please use this Discussions thread for questions and comments on article https://www.systemverilog.io/ddr4-basics</div>

Hi,
I have a question about your 2-rank-setup example, I assume that each rank has a 16-bit data width, if I follow your diagram, can I expect that the processor and ddr controller/phy inside the connecting SoC should also have a 16-bit data bus? In other words, is that possible for the SoC to have a processor of 32-bit data bus but a DDR controller/phy of a 16-bit data bus  and it still works in your example?

**Comment by subbdue** [comment]
Hi @jerryduan100 .. I'm not sure I understand your question entirely. But let me try to answer it anyway. 

In the article, the "2-Rank Setup" example is referring to the interface between **DDR PHY** and the **external memory chip**.  So in the 2-Rank Setup example, the PHY will have DQ[15:0] and CS_n[1:0], i.e., 16-bit data bus and 2-bit Chip Select, to choose 1st Rank or 2nd Rank.

Now, the interface between the SoC's internal block (let's call this the **client interface**) and the DDR Controller can be any arbitrary width. It can be 32, 64, 256, 512, etc. Usually there is a data-converter block or something like an AXI interface between the **Client block** and the **DDR Controller**. 

Also, note that in a typical use case the Reads/Writes from/to the memory are in BL8 Mode (Burst Length 8). So with each read operation the controller actually receives 8x16-bits = 128-bits of data back from the memory. Based on your question if the interface between the SoC and Controller is 32-bits, then the data converter logic needs to split the data and return it over 4-clocks to the SoC.

_PS: BL8 is just one of the mode, the memory can be configured to other modes as well._

**Comment by jerryduan100** [comment]
Awesome! It is very helpful. The key is that the read operation is burst oriented, and it is the data-converter logic's responsibility to split the data and return the proper portion to the internal client (e.g, a 32-bit data bus processor). I didn't really understand "burst" until now. Thank you very much!
